// Basic setup
const SET_ACCOUNT_DETAILS = "SET_ACCOUNT_DETAILS";
const SET_PAWN_SHOP_CONTRACTS = "SET_PAWN_SHOP_CONTRACTS";

// Pawns
const SET_PAWNS = "SET_PAWNS";

// Loans
const SET_LOANS = "SET_LOANS";

// NFTS
const SET_NFTS = "SET_NFTS";

export {
  SET_ACCOUNT_DETAILS,
  SET_PAWN_SHOP_CONTRACTS,
  SET_PAWNS,
  SET_LOANS,
  SET_NFTS,
};
